-- nomor 1
SELECT P.NAME AS "Nama", SUM(T.TOTAL*I.PRICE::INTEGER) AS "Total" FROM PERSONS P, ITEMS I, TRANSACTIONS T WHERE P.ID = T.PERSON_ID AND I.ID = T.ITEM_ID GROUP BY P.NAME;

-- nomor 2 
SELECT SUM(T.TOTAL*I.PRICE::INTEGER) AS "Total", TO_CHAR(T.DATE, 'Month') AS "Month", TO_CHAR(T.DATE, 'YYYY') AS "Year" FROM ITEMS I, TRANSACTIONS T WHERE I.ID = T.ITEM_ID GROUP BY TO_CHAR(T.DATE, 'Month'), TO_CHAR(T.DATE, 'YYYY');

-- nomor 3 
SELECT P.NAME AS "Nama", COUNT(DISTINCT T.ITEM_ID) AS "Jumlah Transaksi Unik" FROM PERSONS P, ITEMS I, TRANSACTIONS T WHERE P.ID = T.PERSON_ID AND I.ID = T.ITEM_ID GROUP BY P.NAME ORDER BY P.NAME ASC;